# Generated by Django 3.2.9 on 2021-12-10 02:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 10, 2, 14, 26, 291763, tzinfo=utc)),
        ),
    ]
